name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create file
        run: cat  /home/runner/work/GithubActionsSample/app/google-services.json | base64
      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA >  /home/runner/work/GithubActionsSample/app/google-services.json
      - name: Build and Deploy Debug
        run: ./gradlew assembleDebug appDistributionUploadDebug
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
