name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Ensure the app directory exists (using the GITHUB_WORKSPACE env var)
      - name: Ensure app directory exists
        run: mkdir -p "$GITHUB_WORKSPACE/app"

      # Create google-services.json from your secret
      - name: Create google-services.json from secret
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$DATA" > "$GITHUB_WORKSPACE/app/google-services.json"
      - name: Build and Deploy Debug
        run: ./gradlew assembleDebug appDistributionUploadDebug
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
